### ISSUE TITLE
Tracking issue for project re-organization and cleanup

### ISSUE THREAD

**Issue by poga** [ailabstw/go-pttai#245]
This is a tracking issue for the on-going project re-organization and cleanup.

**Steps:**
- [ ] Migrate to Go modules #220 
- [ ] Extract standalone `ptt.ai-core` module. #244 
- [ ] end-to-end test for `ptt.ai-core`
- [ ] replace bundled `log` module with upstream, possibly a fork

**Related issues:**

- [ ] Remove ethereum p2p. #216

**Unresolved questions:**

- [ ] Figure out a better naming for nodeID/userID architecture
  * for better recognition.

**Comment by poga** [comment]
#253 needs to be resolved first before migrating to go module

**Comment by poga** [comment]
lots of progress is done in https://github.com/ailabstw/go-pttai/pull/266 and https://github.com/ailabstw/go-pttai/pull/267
